vim.cmd "colorscheme gruvbox"
-- vim.cmd "highlight Normal guibg=none"
-- vim.cmd "highlight SignColumn guibg=#282828"
-- vim.cmd "highlight SignColumn ctermbg=black"
-- vim.cmd "highlight WinSeparator guibg=black"
-- vim.cmd "highlight WinSeparator guifg=#282828"
